language: node_js
sudo: required
dist: trusty
node_js:
  - 'node'

addons:
  code_climate:
    repo_token: be0d4eb28896062ed176b9b07859cfba24033f9bc9caaad20749ea32fd5c5bf4
    chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install codeclimate-test-reporter

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

after_script:
- codeclimate-test-reporter < coverage/lcov.info